// to add project to server's database
export const ADD_PROJECT_TO_DATABASE = "ADD_PROJECT_TO_DATABASE";
export const GET_ALL_PROJECTS_FROM_DATABASE = "GET_ALL_PROJECTS_FROM_DATABASE";
export const ADD_ALL_PROJECTS_FROM_DATABASE_TO_STORE =
  "ADD_ALL_PROJECTS_FROM_DATABASE_TO_STORE";
export const ADD_NEW_PROJECT_FROM_DATABASE_TO_STORE =
  "ADD_NEW_PROJECT_FROM_DATABASE_TO_STORE";
// delete below
export const UPDATE_CURRENT_PROJECT_IN_STORE =
  "UPDATE_CURRENT_PROJECT_IN_STORE";
//   export const UPDATE_CURRENT_PROJECT_IN_STORE =

export const GET_CURRENT_PROJECT_FROM_DATABASE =
  "GET_CURRENT_PROJECT_FROM_DATABASEC";

// issue actions
export const ADD_ISSUE_TO_PROJECT_IN_DATABASE =
  "ADD_ISSUE_TO_PROJECT_IN_DATABASE";
export const UPDATE_ASSIGNEE_FOR_ISSUE_IN_DATABASE =
  "UPDATE_ASSIGNEE_FOR_ISSUE_IN_DATABASE";

// action to update  reqStatusReturnedFromServer: "", reqMessageReturnedFromServer: null,
export const UPDATE_REQ_INFO_RETURNED_FROM_SERVER =
  "UPDATE_REQ_INFO_RETURNED_FROM_SERVER";
